# Generated by Django 5.0 on 2025-12-02 19:56

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('localizacao', models.TextField()),
                ('horario_funcionamento', models.CharField(max_length=100)),
                ('taxa_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='parques/')),
                ('dias_aberto', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default=[], max_length=78)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parque')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('ativo', models.BooleanField(default=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parque')),
            ],
        ),
        migrations.CreateModel(
            name='Trilhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('dificuldade', models.CharField(choices=[('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Difícil', 'Difícil')], max_length=30)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='trilhas/')),
                ('ativo', models.BooleanField(default=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parque')),
            ],
        ),
    ]
