# Generated by Django 5.2.8 on 2025-11-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parque',
            name='horario_abertura',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='horario_fechamento',
        ),
    ]
